CC = gcc
CFLAGS = -Wall
TARGET = array_struct_person
SOURCE = array_struct_person.cc

all: $(TARGET)

$(TARGET): $(SOURCE)
	$(CC) $(CFLAGS) -o $(TARGET) $(SOURCE)

clean:
	rm -f $(TARGET)

.PHONY: all clean

